name: Docker Image CI

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  
  build_and_push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    
    - name: Run Unit Tests
      run: make test
    
    - name: Run Integration Tests
      run: make integration_test
    
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v3.4.1
      with:
        images: salesforce/kube-synthetic-scaler
        flavor: |
          latest=true
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
