name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  tests:
    name: Run Golang Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Install Kubebuilder for Integration Tests
      run: |
        curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_$(go env GOOS)_$(go env GOARCH).tar.gz"
        tar -zxvf kubebuilder_2.3.1_$(go env GOOS)_$(go env GOARCH).tar.gz
        mv kubebuilder_2.3.1_$(go env GOOS)_$(go env GOARCH) kubebuilder && sudo mv kubebuilder /usr/local

    - name: Run Unit Tests
      run: make test

    - name: Run Integration Tests
      run: make integration_test
