name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  tests:
    name: Run Golang Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Run Unit Tests
      run: make test

    - name: Run Integration Tests
      run: make integration_test
